### PR TITLE
Added config file for host and ip

### PR DESCRIPTION
**Pull request by LameLemon**
## Changes
* Added JSON config file
* Host and ip passed into Server constructor

## Summary
Partially addresses issue #10 adding a JSON file and parsing it in `app.py` makes it easier to add functionality in the future.

### CODE REVIEW

**Comment by klattimer** [comment]
Could you pass the whole config object to server? Not just the host/port - then we can make it available there generally, maybe some sanity checks on the values in server too. Then I'll happily merge this.

**Comment by LameLemon** [comment]
Sure thing, I'll add some checks for ipv4 and ipv6 addresses and pass in the entire dictionary into the class`Server`

**Comment by klattimer** [comment]
Do you want another task to work on? I can assign something to you if you like?

**Comment by LameLemon** [comment]
It's cool, I've started changing the css yesterday to have a dark theme because anything I use has to have a dark theme : ) . If you want I could include the option to select the css file in `config.json`.

**Comment by klattimer** [comment]
Yeah, please do that. Would be nice to have some simple theming, but I've got plans for the UI in the future so keep abreast of changes there.

**Comment by klattimer** [comment]
For the dark theme how much are you changing? It might make sense to start a :root colour palette in the CSS, so you only have to change that, and that way we can simplify the CSS quite a bit. 

I already need that css file splitting into bits to support each unique thing, instead of it all piled together in the way that it is.

**Comment by LameLemon** [comment]
Definitely, this is how the root currently looks after the changes I've made. I'll work on it a bit more, would you want me to make a pull request for this or hold off till you make any changes?
```
:root {
    --base-size: 240px;
    --body-bg: rgba(232, 217, 183, 0.3);
    --widget-bg: rgba(255,255,255,0.7);
    --inner-widget-bg: rgba(255,255,255,0.9);
    --header-bg: #565654;
    --widget-grid-header-bg: white; 
    --menu-bg: #E0DBD2;
    --data-table-color: black;
    --info-table-color: black;
    --menu-a-color: rgba(0,0,0,0.6);
    --menu-a-hover-color: rgba(255,255,255,0.8);
    --logfile-color: black;
    --logfile-hover-bg: rgba(0,0,0,0.03);
}
```

**Comment by klattimer** [comment]
Take a look at my most recent commits I think it's a bit nicer. Also, can we move this discussion to another issue.

**Pull request merged**
